title: The Luna Format
#email:
description: >- # this means to ignore newlines until "baseurl:"
  The Luna Format for Doomtrooper CCG.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fiskhandlarn.github.io/doomtrooper.lu/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima

minima:
  date_format: "%Y-%m-%d"
